# fly.toml app configuration file generated for silverstone on 2023-08-24T09:53:38-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "silverstone"
primary_region = "sjc"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
